# railway.toml

[build]
# Install Python and other necessary build tools before running the build
nixpacks = { 
    install = ["python3", "build-essential"], 
    build = "npm install && npm rebuild sqlite3 --build-from-source"
}

[start]
# Command to start your application
cmd = "npm start"
